# Generated by Django 4.2.5 on 2023-11-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='isim',
            field=models.CharField(max_length=50, verbose_name='İsminizi Giriniz'),
        ),
    ]
