# Generated by Django 4.2.5 on 2023-11-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_kullanici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='isim',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='soyisim',
            field=models.CharField(max_length=250),
        ),
    ]
